AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Tarius: CFN Template To Create A S3 Table Encrypted With Customer Managed KMS Key With Or Without A Folder. 

Metadata:
  TemplateName: s3-stack.yaml
  TemplateType: S3 bucket with optionally default folder
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Tarius
  Modification History:
    - 1.0.0  - July 13, 2023   -- Initial Version 
  Resources: 
    - S3 Bucket Encrypted With Customer Managed KMS Key with Bucket 
      Policy to grant access to Lambda Execution Role in another Account.
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
      - ProjectName
      - Environment
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Key:"
      Parameters:
      - KmsMasterKeyAlias
    #################################### AWS Account ###############################################
    - Label: 
        default: "Account-B:"
      Parameters:
      - AWSAccountB
    #################################### S3 Bucket #################################################
    - Label:
        default: "S3 Configuration"
      Parameters:
      - S3BucketBaseName
      - S3BucketBlockPublicAcls
      - S3BucketBlockPublicPolicy
      - S3BucketIgnorePublicAcls
      - S3BucketRestrictPublicBuckets
      ################################## SNS #######################################################
    - Label:
        default: "SNS Topic:"
      Parameters:
      - SNSTopicArn
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      #################################### AWS Account Id ############################################
      AWSAccountB: 
        default: "Account-B Id:"
      #################################### KMS Key ###################################################
      KmsMasterKeyAlias: 
        default: "KMS Key Alias."
      ################################## S3 Bucket #################################################
      S3BucketBaseName:
        default: "S3 Bucket Base Name."
      S3BucketBlockPublicAcls:
        default: "Allow BlockPublicAcls"
      S3BucketBlockPublicPolicy:
        default: "Allow BlockPublicPolicy"
      S3BucketIgnorePublicAcls:
        default: "Allow IgnorePublicAcls"
      S3BucketRestrictPublicBuckets:
        default: "Allow restrictPublicBuckets"
      ################################## SNS #######################################################
      SNSTopicArn:
        default: "The SNS Topic Arn."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: project
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod" 
  ###################################### AWS Account ###############################################
  AWSAccountB:
    Default: 508634243190
    Type: Number
    Description: The AWS First account where the S3 bucket will be created.
  ###################################### KMS Key ###################################################
  KmsMasterKeyAlias:
    Default: "SB-KMS"
    Description: "The KMS Master Key Alias To Be Used For Server Side Encryption."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: "The length of the KMS Key Alias should be beteen 5 and 20 and can only contain lowercase alphanumeric characters and dash."
  ###################################### S3 Bucket #################################################
  S3BucketBaseName:
    Default: some-s3-bucket-name
    Description: "The S3 Bucket Base Name For The Source Data, The Region Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  S3BucketBlockPublicAcls:
    Default: true
    Description: "Allow Block Public Acls"
    Type: String
    AllowedValues: [true, false]
  S3BucketBlockPublicPolicy:
    Default: true
    Description: "Allow Block Public Policy"
    Type: String
    AllowedValues: [true, false]
  S3BucketIgnorePublicAcls:
    Default: true
    Description: "Allow Ignore Public Acls"
    Type: String
    AllowedValues: [true, false]
  S3BucketRestrictPublicBuckets:
    Default: true
    Description: "Allow Restrict Public Buckets"
    Type: String
    AllowedValues: [true, false]
  ###################################### SNS with Email Subscription ###############################
  SNSTopicArn:
    Default: "arn:aws:sns:us-east-1:807724355529:sunflower-lambda-integration-topic-devl-us-east-1"
    Description: "The Arn of the SNS Topic."
    Type: String
    MinLength: 10
    MaxLength: 100
    # AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 100, must be a valid SNS Topic Arn"
Resources:
  ###################################### S3 Bucket #################################################
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${S3BucketBaseName}-${AWS::AccountId}-${Environment}-${AWS::Region}"
      BucketEncryption:
          ServerSideEncryptionConfiguration: 
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault: 
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Sub 'alias/${KmsMasterKeyAlias}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: !Ref S3BucketBlockPublicAcls
        BlockPublicPolicy: !Ref S3BucketBlockPublicPolicy
        IgnorePublicAcls: !Ref S3BucketIgnorePublicAcls
        RestrictPublicBuckets: !Ref S3BucketRestrictPublicBuckets
      NotificationConfiguration:
        TopicConfigurations:
        - Topic: !Ref SNSTopicArn
          Event: 's3:ObjectCreated:*'
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key:  Environment
          Value: !Ref Environment
  S3BucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: "Set replication permissions for objects"
          Effect: Allow
          Principal:
            AWS: 
              - !Sub 'arn:${AWS::Partition}:iam::${AWSAccountB}:role/${ProjectName}-lambda-execution-role' ## role/${ProjectName}-lambda-execution-role
          Action:
          - s3:GetObject
          - s3:ListBucket
          Resource: 
          - !Sub 'arn:${AWS::Partition}:s3:::${ProjectName}-${S3BucketBaseName}-${AWS::AccountId}-${Environment}-${AWS::Region}'
          - !Sub 'arn:${AWS::Partition}:s3:::${ProjectName}-${S3BucketBaseName}-${AWS::AccountId}-${Environment}-${AWS::Region}/*'
Outputs:
  S3BucketArn:
    Description: The S3 Bucket Arn.
    Value: !GetAtt S3Bucket.Arn
