AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Carnation: CFN Template to create a Lambda Function. 

Metadata:
  TemplateName: lambda-function-stack.yaml
  TemplateType: Lambda Function to access a S3 bucket in another account using Bucket policy
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Carnation
  Modification History:
    - 1.0.0  - Jul 13, 2023  -- Initial Version 
  Resources: 
    - Lambda Function
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
      - ProjectName
      - Environment
    #################################### Code Repository Bucket ####################################
    - Label: 
        default: "Code Repository S3 Bucket:"
      Parameters: 
      - CodeRepositoryS3Bucket
    #################################### AWS Account ###############################################
    - Label:
        default: The Account Id where the S3 Bucket will be created
      Parameters: 
      - AWSAccountA
    #################################### KMS Key ###################################################
    - Label:
        default: The Arn of the KMS Key in Account-A
      Parameters: 
      - KmsMasterKeyArn
    #################################### Lambda Function ###########################################
    - Label:
        default: "Lambda Function Configuration:"
      Parameters: 
      - LambdaExecutionRoleBaseName
      - LambdaExecutionPolicyBaseName
      - LambdaHandlerPath
      - LambdaFunctionTimeoutSecs
      - LambdaRuntime
      - LambdaFunctionMemory
      - LambdaFunctionCodeKey
      - LambdaFunctionBaseName
      - LambdaFunctionDescription
      # - LambdaReservedConcurrency
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment: 
        default: "Environment Name."
      ################################## Code Repository Bucket ####################################
      CodeRepositoryS3Bucket:
        default: "S3 Bucket Name used as code repository."
      ################################## AWS Account ###############################################
      AWSAccountA:
        default: The Account Id where the S3 Bucket will be created
      ################################## KMS Key ###############################################
      KmsMasterKeyArn: 
        default: "The Arn of the KMS Key to be used to encrypt an object in S3"
      #################################### SNS Topic ###############################################
      SNSTopicBaseName:
        default: "The SNS Topic Name."
      ################################## Lambda Function ###########################################
      LambdaExecutionRoleBaseName: 
        default: "Lammba Function Execution Role Base Name."
      LambdaExecutionPolicyBaseName:
        default: "Lammba Function Execution Policy Base Name."
      LambdaHandlerPath: 
        default: "Lambda Handler Path."
      LambdaFunctionTimeoutSecs:
        default: "Lambda Function Timeout in Seconds."
      LambdaRuntime: 
        default: "Lambda Runtime."
      LambdaFunctionMemory:
        default: "Lambda Fuction Memory."
      LambdaFunctionCodeKey: 
        default: "Lambda Function Code Zip File Key."
      LambdaFunctionBaseName:
        default: "Name of the Lambda Function."
      LambdaFunctionDescription:
        default: "Lambda Function Description." 
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: sunflower
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### Code Repository Bucket ####################################
  CodeRepositoryS3Bucket:
    Default: subhamay-projects-repository-us-east-1
    Description: "S3 Bucket Storing The Lambda Code."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 63, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  ###################################### AWS Account ###############################################
  AWSAccountA:
    Default: 807724355529
    Type: Number
    Description: The AWS Second account where the S3 bucket will be created.
  ###################################### KMS Key ###################################################
  KmsMasterKeyArn:
    Default: "arn:aws:kms:us-east-1:807724355529:key/e4c733c5-9fbe-4a90-bda1-6f0362bc9b89"
    Description: "The Arn of the KMS Master Key To Be Used For Server Side Encryption In Account-A"
    Type: String
    MinLength: 30
    MaxLength: 100
    AllowedPattern: "[a-z0-9:/-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and should contain lower case alphabets, numbers and dash." 
  ###################################### Lambda Function ###########################################
  LambdaExecutionRoleBaseName:
    Default: lambda-execution-role
    Description: Lambda execution IAM role name.
    Type: String
    MinLength: 5
    MaxLength: 50
    AllowedPattern: "[a-zA-Z-]*"
    ConstraintDescription: "The length should be between 5 and 50, , must contain only lowercase letters,numbers and hyphen (-)."
  LambdaExecutionPolicyBaseName:
    Default: lambda-execution-policy
    Description: Lambda execution IAM policy name.
    Type: String
    MinLength: 5
    MaxLength: 50
    AllowedPattern: "[a-zA-Z-]*"
    ConstraintDescription: "The length should be between 5 and 50, , must contain only lowercase letters,numbers and hyphen (-)."
  LambdaHandlerPath:
    Default: lambda_function.lambda_handler
    Description: The Lambda handler function.
    Type: String
    MinLength: 10
    MaxLength: 50
    AllowedPattern: "[a-zA-Z0-9_.]*"
    ConstraintDescription: "Must be between 10 and 50 characters long and should be a valid handler path."
  LambdaRuntime:
    Default: python3.8
    Description: "Lambda Runtime (Python 3.7, 3.8 or 3.9)"
    Type: String
    AllowedValues: [python3.7 ,python3.8, python3.9]
    ConstraintDescription: "The Lambda runtime should be either Python 3.7, 3.8 or 3.9"
  LambdaFunctionTimeoutSecs:
    Default: 300
    Description: Lambda function timeout period in seconds.
    Type: Number
    MinValue: 3
    MaxValue: 900
    ConstraintDescription: "The Lambda timeout period should be between 3 and 900 seconds."
  LambdaFunctionMemory:
    Default: 256
    Description: "The Lambda function memory in MB."
    Type: Number
    MinValue: 128
    MaxValue: 10240
    ConstraintDescription: "The Lambda Memory should be between 128 and 10240."
  LambdaFunctionCodeKey:
    Default: 0018-sunflower/code/python/lambda_function.zip
    Description: "The zip file name containing the processing Lambda code."
    Type: String
    MinLength: 10
    MaxLength: 100
    AllowedPattern: "[a-zA-Z0-9-/_.]*"
    ConstraintDescription: "The length should be between 10 and 100, must contain only lowercase letter,numbers,dash, dot, underscore"
  LambdaFunctionBaseName:
    Default: "processing-lambda"
    Description: "Processing Lambda function base name."
    Type: String
    MinLength: 15
    MaxLength: 50
    AllowedPattern: "[a-z-]*"
    ConstraintDescription: The length should be between 15 and 50, must contain only lowercase letters,numbers and dash(-) and should start with a letter.
  LambdaFunctionDescription:
    Default: The Lambda Function triggered via SNS Subscription on upload of a file to S3 bucket.
    Description: "The Lambda Function Description."
    Type: String
    MinLength: 30
    MaxLength: 200
    AllowedPattern: "^[A-Z][a-zA-Z0-9 .,]*$"
    ConstraintDescription: The length should be between 30 and 300, must contain only lowercase letters,space( ) and dot(.) and should start with an uppercase letter.
  ###################################### S3 Bucket #################################################
  S3BucketBaseName:
    Default: bucket
    Description: "The Name Of S3 Bucket to store the data."
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash and should start with a letter."
  ###################################### SNS Topic #################################################
  SNSTopicBaseName:
    Default: "lambda-integration-topic"
    Description: "The Base Name Of The Sns Topic."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
Resources:
  ###################################### Lambda Function ###########################################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${LambdaExecutionRoleBaseName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-${LambdaExecutionPolicyBaseName}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowCloudWatchLogStream
              Effect: Allow
              Action: 
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: 
              - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ProjectName}-${LambdaFunctionBaseName}-${Environment}-${AWS::Region}:*'
            - Sid: AllowReadS3Bucket 
              Effect: Allow
              Action: 
              - s3:ListBucket
              - s3:GetObject
              Resource: 
              - !Sub 'arn:${AWS::Partition}:s3:::${ProjectName}-${S3BucketBaseName}-${AWSAccountA}-${Environment}-${AWS::Region}'
              - !Sub 'arn:${AWS::Partition}:s3:::${ProjectName}-${S3BucketBaseName}-${AWSAccountA}-${Environment}-${AWS::Region}/*'
            - Sid: AllowKMSDecrypt
              Effect: Allow
              Action: 
              - kms:Decrypt
              - kms:Encrypt
              Resource: !Ref KmsMasterKeyArn
            - Sid: AllowSESSendMail
              Effect: Allow
              Action: 
              - ses:SendEmail
              Resource: !Sub "arn:${AWS::Partition}:ses:${AWS::Region}:${AWS::AccountId}:identity/*"
      Tags: 
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: EnvironmentName
          Value: !Ref Environment
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: !Ref LambdaRuntime
      FunctionName: !Sub '${ProjectName}-${LambdaFunctionBaseName}-${Environment}-${AWS::Region}'
      Description: !Ref LambdaFunctionDescription
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: !Ref LambdaHandlerPath
      Code:
        S3Bucket: !Ref CodeRepositoryS3Bucket
        S3Key: !Ref LambdaFunctionCodeKey
      Timeout: !Ref LambdaFunctionTimeoutSecs
      MemorySize: !Ref LambdaFunctionMemory
      TracingConfig:
        Mode: Active
      Environment:
        Variables:
          S3_BUCKET_NAME: !Sub '${ProjectName}-${S3BucketBaseName}-${AWSAccountA}-${Environment}-${AWS::Region}'
          SENDER: "senderb@email.com"
          RECIPIENT: "recipient@email.com"
          CONFIGURATION_SET: ConfigSet
          CHARSET: "UTF-8"
          SUBJECT: "AWS SES and Python Pandas Demo"
      Layers:
        - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-pandas:11
      Tags: 
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key:  Environment
          Value: !Ref Environment
  LambdaInvokePermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWSAccountA}:${ProjectName}-${SNSTopicBaseName}-${Environment}-${AWS::Region}'
      FunctionName: !GetAtt LambdaFunction.Arn
  SNSSubscription:
    DependsOn:
         - LambdaInvokePermission
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt LambdaFunction.Arn
      TopicArn: !Sub "arn:${AWS::Partition}:sns:${AWS::Region}:${AWSAccountA}:${ProjectName}-${SNSTopicBaseName}-${Environment}-${AWS::Region}"
Outputs:
  LambdaFunctionArn: 
    Description: The Arn of the Lambda Function
    Value: !GetAtt LambdaFunction.Arn
  SNSSubscriptionArn: 
    Description: The Arn of the SNS Subscription
    Value: !Ref SNSSubscription
